### ISSUE TITLE
Name for modules

### ISSUE THREAD

**Issue by scaronni** [opengapps/aosp_build#18]
Hello,

I would like to finish contributing the remaining overrides for the other Google modules.
I'm a bit confused about the module names. I'm looking at the following locations:

* https://github.com/opengapps/opengapps/wiki/Package-Comparison
* https://github.com/opengapps/aosp_build/tree/master/modules

The names inside the aosp_build do not match with the ones in the "normal" opengapps installer. I see "PrebuiltXXX", "GoogleXXXPrebuilt" or "GoogleXXX" names.

As an example, the calculator is missing and I would like to add it; how should I name it under the modules directory? Any pointer?

Thanks,
--Simone

**Comment by Blystad** [comment]
Hey,

I generated all the modules a while ago, and since then a few new packages has been introduced. Adding them is fairly easy.

1) Find the package name, in either opengapps/all or one of the architecture specific versions (e.g. opengapps/arm ). For the calculator this is [com.google.android.calculator](https://github.com/opengapps/all/tree/master/app/com.google.android.calculator)

2) Create a directory in modules/ (e.g. Calculator) and copy an Android.mk from another module

3) Substitute the LOCAL_MODULE, LOCAL_PACKAGE_NAME and LOCAL_MODULE_PATH with the correct values.

4) Add them to `opengapps-packages.mk` at the correct place.

Here is a example Android.mk for the Calculator:
```
LOCAL_PATH := .
include $(CLEAR_VARS)
LOCAL_MODULE := CalculatorGoogle
LOCAL_PACKAGE_NAME := com.google.android.calculator
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/app

include $(BUILD_GAPPS_PREBUILT_APK)
```

**Comment by scaronni** [comment]
Ah ok, will do then. I thought that for point 2 the name had to be something specific from a naming convention. If this is not the case, would you accept a patch to make naming a bit more consistent?

All the modules could have their "base name" as folder name. For example remove all "Prebuilt" prefixes, add "Google" as a prefix everwhere and not as a suffix, rename those obscure modules (GCS, Velvet, Bugle, etc.)? Or they could be named exactly as they are in the opengapps/opengapps repository.

**Comment by mfonville** [comment]
You can find the "obscure" names that are used for each application in https://github.com/opengapps/opengapps/blob/master/scripts/inc.buildtarget.sh

The names are chosen as Google uses them on the Nexus stock images. Sometimes these are indeed (very) weird.

**Comment by Blystad** [comment]
Lets have the `LOCAL_MODULE` tag follow what Google uses on Nexus images, for sanity. 

I don't mind what the directories in `aosp_build/modules` are named.

**Comment by scaronni** [comment]
Perfect, will use those names! Thanks.
