### ISSUE TITLE
Issue with gapps-copy-to-system

### ISSUE THREAD

**Issue by Fuzion24** [opengapps/aosp_build#23]
in core/definitions.mk, it looks like there is a bug with the gapps-copy-to-system not properly appending a ":system" 

https://github.com/opengapps/aosp_build/blob/master/core/definitions.mk#L41

build/core/tasks/vendor_module_check.mk:63: *** Error: vendor PRODUCT_COPY_FILES file "vendor/opengapps/sources/all/etc/permissions/com.google.android.media.effects.xml:system/etc/permissions/com.google.android.media.effects.xml" has unknown owner.  Stop.

**Comment by Blystad** [comment]
Nah, this is because hammerhead seems to restrict vendor files more then others. See #22 

This happens because the file isn't in one of the whitelisted vendor folders (See `_vendor_owner_whitelist` in `build/core/tasks/vendor_module_check.mk`), but this check only happens if `PRODUCT_RESTRICT_VENDOR_FILES` is set.

Google probably have a build target where the `PRODUCT_RESTRICT_VENDOR_FILES` is set to false.

See this post for more info: https://groups.google.com/forum/#!topic/android-building/BG9duJK-ObU
