### ISSUE TITLE
leanback support

### ISSUE THREAD

**Issue by ric96** [opengapps/aosp_build#47]
Can you pleas add support to build for leanback
' ' '
ric@ric-ubuntu:~/androidx86tv$ lunch android_x86_64-userdebug
vendor/google/build/config.mk:34: **\* GAPPS_VARIANT leanback was not found. Use of one of pico,nano,micro,mini,full,stock,super.  Stop.
' ' '

**Comment by jamuir** [comment]
@ric96:  do you mean that you would like the apk `com.google.android.leanbacklauncher` to be one of the apks included in opengapps?

**Comment by ric96** [comment]
I meant the way we can have other gapps pico nano etc included in our aosp buils system and buid our image using them like shown here: https://github.com/opengapps/aosp_build

I want the same for tvstock so that we can have a android tv like rom using that, and afaik tvstock does include leanback launcher.

**Comment by jamuir** [comment]
understood.  Support for a `tvstock` variant is requested in #118.

**Comment by jamuir** [comment]
closing.  We will continue to track this via issue #118 and its associated PR (#158).

**Comment by Road-Drum** [comment]
I dont want to open q new issue, but if I want to include `tvstock` packages to `pico`, what's the corresponding packages to be added using `GAPPS_PRODUCT_PACKAGES +=` according to [TVStock Package Comparison](https://github.com/opengapps/opengapps/wiki/TVStock-Package)?

Adding this to Raspberry Pi 3 AOSP build. Manually adding package seems to be a good way for me since RPI3's limited RAM means that I'll be skipping Games, Music etc
